name: Publish
on:
  workflow_dispatch:
  push:
    tags: ["*"]

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml

  publish:
    runs-on: ubuntu-latest
    needs: tests
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ndfeb/httpd-slim
        tags: |
          type=semver,pattern=v{{version}}
          type=sha,prefix=

    - run: echo "steps.meta.outputs.tags = ${{ steps.meta.outputs.tags }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        platforms: linux/amd64,linux/arm64
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
