name: Test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main, dev]
    # For tags, will be called from publish workflow
    tags-ignore: ["**"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run test script
      run: ./test.sh
